baseURL = "https://anonimitoraf.github.io/public"
languageCode = "en-us"
title = "Ramblings, Brain Dumps and Everything in between"
theme = "github-style"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
