#+TITLE: Habitual Tasks
#+HUGO_BASE_DIR: ..
#+HUGO_SECTION: post
#+HUGO_CUSTOM_FRONT_MATTER: :date 2022-01-30 :pin true :summary "Tasks that will form into habits that I want to have"
#+HUGO_TAGS: "self-improvement"

NOTE: This is a continually-evolving blog post and probably won't ever be "finished"

* Read this blog post every morning
Helps set the focus for the day. Goes best with watching [[yt:https://www.youtube.com/watch?v=wupToqz1e2g][Pale Blue Dot]] (to remind me to be humble).

* Write something substantial everyday
** Why?
I want to get much better and more importantly, more comfortable with writing. I don't see any other way than: writing, A LOT.

I'm imposing on myself to write a semi-structured blog post, an unorganized brain dump, or really, anything, to make sure I continually sharpen my writing skills.

On that days that I don't write anything, there has to be a damn good excuse for not doing so. Better yet, maybe I can write down (in a global blog post or somewhere else) my excuse for not writing on that day.
** Writing as a way of caching information
I sometimes get confused easily. Something may make sense to me at the time, then, a day or so later, I forget about my understanding of it (and have to re-understand it).

So, I believe, writing down my thought processes and understanding of something can mitigate this. Similar to caching in software - saves computing resources, time, etc. in re-calculating something that's previously calculated.
And yes, this analogy probably breaks at some point, but I won't worry about it for now.
* Watch/read something educational and write about it
Some people out there have honed the skill to help others gain intuition by distilling, re-framing and/or visualizing complex topics. Pair this with the internet and you have the opportunity to learn efficiently, at your fingertips. For example:
- [[yt:https://www.youtube.com/c/3blue1brown][3blue1brown]]
- [[yt:https://www.youtube.com/c/veritasium][Veritasium]]
I'm usually short on time. I have a day job as a software engineer, consult for another company, contribute to open source and have multiple side projects on the side. So, want as I may to learn via reading papers/texts, time doesn't permit me to do so. Although, in the off-chances that I do get some time to read (maybe during commute, etc), I'll write about them too.
