#+TITLE: So, How Exactly Do You Write Good Blog Posts?
#+HUGO_BASE_DIR: ..
#+HUGO_CUSTOM_FRONT_MATTER: :date "2021-07-09" :pin true :summary "A meta-blog post on how to write good blog posts"

* Key Points
** Be concise - Optimize for reading
You might write and/or edit a blog post once, twice or even 5x but ...

... in comparison your readers might read it tens, hundreds or even thousands of times (suppose it got popular).
** Know who your target readers are - Empathise with them
For example:

Instead of writing "medical jargon-filled" posts with the intention of targeting medical-laymen readers...

... try using analogies that you think might resonate with the /average/ person
** Examples help
Descriptions and definitions can sometimes be too /abstract/ for the reader to fully grasp.

For example:
#+begin_quote
The sorites paradox is a paradox that arises from vague predicates
#+end_quote

*What?!* Ok, here's an example:
#+begin_quote
1 grain of wheat does not make a heap.
If 1 grain doesn't make a heap, then 2 grains don't.
If 2 grains don't make a heap, then 3 grains don't.
...
If 999,999 grains don't make a heap, then 1 million grains don't.
#+end_quote
